version: '3.3'
services:
  leap-ledger-server:
    container_name: leap-ledger-server
    image: xiaozirun/leap-ledger:${SERVICE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.build
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - ./log:/go/LeapLedger/log
      - ./docs:/go/LeapLedger/docs
    networks:
      - leap-ledger-network
    depends_on:
      - leap-ledger-mysql
      - leap-ledger-nats
      - leap-ledger-redis
  leap-ledger-mysql:
    container_name: leap-ledger-mysql
    image: mysql:8.0.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: leap_ledger
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    command: >
      bash -c "
      chmod 644 /etc/mysql/conf.d/*.cnf
      && /entrypoint.sh mysqld
      "
    networks:
      - leap-ledger-network
  leap-ledger-redis:
    container_name: leap-ledger-redis
    privileged: true
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis.conf:/redis.conf
      - ./docker/data/redis:/data
    networks:
      - leap-ledger-network
    command: ["redis-server", "/redis.conf"]
  leap-ledger-nats:
    container_name: leap-ledger-nats
    image: nats:latest
    command: -js -sd /data -http_port 8222
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./docker/data/nats:/data
    networks:
      - leap-ledger-network
networks:
  leap-ledger-network: